services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      platforms:
        - linux/amd64
    ports:
      - '5173:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
