/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const MyPageLazyImport = createFileRoute('/my-page')()
const IndexLazyImport = createFileRoute('/')()
const MyPageIntroEditLazyImport = createFileRoute('/my-page/intro-edit')()

// Create/Update Routes

const MyPageLazyRoute = MyPageLazyImport.update({
  path: '/my-page',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/my-page.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const MyPageIntroEditLazyRoute = MyPageIntroEditLazyImport.update({
  path: '/intro-edit',
  getParentRoute: () => MyPageLazyRoute,
} as any).lazy(() =>
  import('./routes/my-page/intro-edit.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/my-page': {
      id: '/my-page'
      path: '/my-page'
      fullPath: '/my-page'
      preLoaderRoute: typeof MyPageLazyImport
      parentRoute: typeof rootRoute
    }
    '/my-page/intro-edit': {
      id: '/my-page/intro-edit'
      path: '/intro-edit'
      fullPath: '/my-page/intro-edit'
      preLoaderRoute: typeof MyPageIntroEditLazyImport
      parentRoute: typeof MyPageLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  MyPageLazyRoute: MyPageLazyRoute.addChildren({ MyPageIntroEditLazyRoute }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/my-page"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/my-page": {
      "filePath": "my-page.lazy.tsx",
      "children": [
        "/my-page/intro-edit"
      ]
    },
    "/my-page/intro-edit": {
      "filePath": "my-page/intro-edit.lazy.tsx",
      "parent": "/my-page"
    }
  }
}
ROUTE_MANIFEST_END */
